class_name CitizenStateProcessor
extends RefCounted


func process_state_behavior(actor: Citizen, delta: float) -> void:
	if actor == null:
		return
	match actor.state:
		Citizen.State.IDLE:
			actor._process_idle_wander(delta)
		Citizen.State.WAITING:
			actor._process_waiting(delta)
		Citizen.State.TO_TREE:
			actor._process_to_source(delta)
		Citizen.State.CHOPPING:
			actor._process_source_work(delta)
		Citizen.State.TO_SAWMILL:
			actor._process_to_workplace(delta)
		Citizen.State.SAWING:
			actor._process_workplace_work(delta)
		Citizen.State.TO_WAREHOUSE:
			actor._process_resource_delivery(delta)
		Citizen.State.WAITING_COURIER:
			actor._process_courier_wait(delta)
		Citizen.State.CONSTRUCTING:
			actor._process_construction(delta)
		Citizen.State.EXCAVATING:
			actor._process_excavation(delta)
		Citizen.State.COURIER_TO_WORKER:
			actor._process_courier_pickup(delta)
		Citizen.State.COURIER_TO_SAWMILL:
			actor._process_sawmill_pickup(delta)
		Citizen.State.COURIER_TO_DEW:
			actor._process_dew_collector_pickup(delta)
		Citizen.State.COURIER_TO_WAREHOUSE:
			actor._process_courier_delivery(delta)
		Citizen.State.TO_HOME:
			actor._process_go_home(delta)
		Citizen.State.RESTING:
			actor._process_resting(delta)
		Citizen.State.TO_CANTEEN:
			actor._process_go_to_canteen(delta)
		Citizen.State.EATING:
			actor._process_eating(delta)
		Citizen.State.TO_FOOD_PICKUP:
			actor._process_food_pickup(delta)
		Citizen.State.TO_CANTEEN_DELIVERY:
			actor._process_canteen_delivery(delta)
		Citizen.State.TO_CANTEEN_WORK:
			actor._process_canteen_work(delta)
		Citizen.State.TO_SCHOOL:
			actor._process_go_to_school(delta)
		Citizen.State.STUDYING:
			pass
		Citizen.State.RESEARCHING:
			actor._process_research(delta)
		Citizen.State.TO_SCHOOL_WORK:
			actor._process_school_work(delta)
		Citizen.State.TO_OFFICIAL_WORK:
			actor._process_official_work(delta)
		Citizen.State.OFFICIAL_WORK:
			pass
		Citizen.State.TO_FACTORY:
			actor._process_to_factory(delta)
		Citizen.State.FACTORY_WORK:
			actor._process_factory_work(delta)
		Citizen.State.TO_PARK:
			actor._process_go_to_park(delta)
		Citizen.State.RELAXING:
			actor._process_relaxing(delta)
		Citizen.State.TO_GATHER:
			actor._process_to_gather(delta)
		Citizen.State.GATHERING:
			actor._process_gathering(delta)
		Citizen.State.TO_CLEANING_PILE:
			actor._process_to_cleaning_pile(delta)
		Citizen.State.CLEANING_PILE:
			actor._process_cleaning_pile(delta)
		Citizen.State.TO_TRADE_PICKUP:
			actor._process_trade_pickup(delta)
		Citizen.State.TO_TRADE_DESTINATION:
			actor._process_trade_destination(delta)
		Citizen.State.TO_EMPLOYMENT_CENTER:
			actor._process_to_employment_center(delta)
		Citizen.State.EMPLOYMENT_PROCESSING:
			actor._process_employment_processing(delta)
		Citizen.State.CANTEEN_WORK:
			pass
		Citizen.State.SCHOOL_WORK:
			pass
		Citizen.State.TO_MARKET_WORK:
			actor._process_market_work_arrival(delta)
		Citizen.State.MARKET_WORK:
			pass
		Citizen.State.TO_CRAFT_WORK:
			actor._process_craft_work_arrival(delta)
		Citizen.State.CRAFT_WORK:
			actor._process_craft_work(delta)
		Citizen.State.TO_CONSTRUCTION_PICKUP:
			actor._process_construction_pickup(delta)
		Citizen.State.TO_CONSTRUCTION_SITE:
			actor._process_construction_delivery(delta)
		Citizen.State.TO_ARRIVAL_ENTRANCE:
			actor._process_arrival_entrance(delta)
		Citizen.State.ARRIVAL_MEETING:
			actor._process_arrival_meeting(delta)
		Citizen.State.TO_ARRIVAL_CENTER:
			actor._process_arrival_center(delta)
		Citizen.State.TO_OUTSIDE_WORK:
			actor._process_outside_work_departure(delta)
		Citizen.State.LEAVING:
			actor._process_leaving(delta)
		Citizen.State.TO_TOILET:
			actor._process_to_toilet(delta)
		Citizen.State.USING_TOILET:
			actor._process_using_toilet(delta)
		Citizen.State.WAITING_FOR_TOILET:
			actor._process_waiting_for_toilet(delta)
		Citizen.State.TO_BUSH:
			actor._process_to_bush(delta)
		Citizen.State.USING_BUSH:
			actor._process_using_bush(delta)
		Citizen.State.AI_MOVING:
			actor._process_ai_moving(delta)
		Citizen.State.WORK_POSITION:
			pass
