extends SceneTree

const TestDomainConstructionScript = preload("res://tests/domain/test_domain_construction.gd")
const TestDomainRoutingScript = preload("res://tests/domain/test_domain_routing.gd")
const TestDomainLogisticsScript = preload("res://tests/domain/test_domain_logistics.gd")
const TestDomainBuildingEditorScript = preload("res://tests/domain/test_domain_building_editor.gd")
const TestDomainEconomyScript = preload("res://tests/domain/test_domain_economy.gd")
const TestDomainLaunchScript = preload("res://tests/domain/test_domain_launch.gd")
const TestDomainGameRuntimeScript = preload("res://tests/domain/test_domain_game_runtime.gd")
const TestDomainNavigationScript = preload("res://tests/domain/test_domain_navigation.gd")
const TestDomainHousingBlueprintsScript = preload("res://tests/domain/test_domain_housing_blueprints.gd")
const TestDomainWorldAssetsScript = preload("res://tests/domain/test_domain_world_assets.gd")
const TestDomainEntityArchetypesScript = preload("res://tests/domain/test_domain_entity_archetypes.gd")
const TestDomainMapEntitiesScript = preload("res://tests/domain/test_domain_map_entities.gd")
const TestDomainMapScatterRemovedScript = preload("res://tests/domain/test_domain_map_scatter_removed.gd")
const TestDomainTerrainScript = preload("res://tests/domain/test_domain_terrain.gd")
const TestDomainTerrainMaterialsScript = preload("res://tests/domain/test_domain_terrain_materials.gd")
const TestSurfaceStateScript = preload("res://tests/features/world/test_surface_state.gd")
const TestTerrainMeshingScript = preload("res://tests/features/world/test_terrain_meshing.gd")
const TestTerrainBrushScript = preload("res://tests/features/world/test_terrain_brush.gd")
const TestMapDocumentScript = preload("res://tests/features/world/test_map_document.gd")
const TestWaterBrushScript = preload("res://tests/features/world/test_water_brush.gd")
const TestWaterFlowScript = preload("res://tests/features/world/test_water_flow.gd")
const TestMapEditorHistoryScript = preload("res://tests/features/world/test_map_editor_history.gd")
const TestDomainTerrainNavigationScript = preload("res://tests/domain/test_domain_terrain_navigation.gd")
const TestDomainWaterScript = preload("res://tests/domain/test_domain_water.gd")
const TestSaveLoadScript = preload("res://tests/test_save_load.gd")
const TestAIFrameworkScript = preload("res://tests/ai/test_ai_framework.gd")
const TestAINeedsScript = preload("res://tests/ai/test_ai_needs.gd")
const TestAIWorkProvidersScript = preload("res://tests/ai/test_ai_work_providers.gd")
const TestAILogisticsScript = preload("res://tests/ai/test_ai_logistics.gd")
const TestAIDomainScript = preload("res://tests/ai/test_ai_domain.gd")

func _init() -> void:
	print("=== All tests ===")
	TestDomainEconomyScript.run_all()
	TestDomainRoutingScript.run_all()
	TestDomainConstructionScript.run_all()
	TestDomainLogisticsScript.run_all()
	TestDomainLaunchScript.run_all()
	TestDomainGameRuntimeScript.run_all()
	TestDomainNavigationScript.run_all()
	TestDomainBuildingEditorScript.run_all()
	TestDomainHousingBlueprintsScript.run_all()
	TestDomainWorldAssetsScript.run_all()
	TestDomainEntityArchetypesScript.run_all()
	print("=== Done ===")
	quit(0)
