extends SceneTree

const TestDomainEconomyScript = preload("res://tests/domain/test_domain_economy.gd")
const TestDomainEnvironmentScript = preload("res://tests/domain/test_domain_environment.gd")
const TestDomainRoutingScript = preload("res://tests/domain/test_domain_routing.gd")
const TestDomainConstructionScript = preload("res://tests/domain/test_domain_construction.gd")
const TestDomainLogisticsScript = preload("res://tests/domain/test_domain_logistics.gd")
const TestDomainLaunchScript = preload("res://tests/domain/test_domain_launch.gd")
const TestDomainGameRuntimeScript = preload("res://tests/domain/test_domain_game_runtime.gd")
const TestDomainNavigationScript = preload("res://tests/domain/test_domain_navigation.gd")
const TestDomainBuildingEditorScript = preload("res://tests/domain/test_domain_building_editor.gd")
const TestZoneAuthoringInvariantsScript = preload("res://tests/domain/test_zone_authoring_invariants.gd")
const TestDomainHousingBlueprintsScript = preload("res://tests/domain/test_domain_housing_blueprints.gd")
const TestDomainWorldAssetsScript = preload("res://tests/domain/test_domain_world_assets.gd")
const TestDomainHarvestSourcesScript = preload("res://tests/domain/test_domain_harvest_sources.gd")
const TestDomainWanderHabitsScript = preload("res://tests/domain/test_domain_wander_habits.gd")
const TestDomainEntityPlacementProbeScript = preload("res://tests/domain/test_domain_entity_placement_probe.gd")
const TestDomainSeasonalEntitiesScript = preload("res://tests/domain/test_domain_seasonal_entities.gd")
const TestDomainBiomeFillScript = preload("res://tests/domain/test_domain_biome_fill.gd")
const TestDomainMapScatterScript = preload("res://tests/domain/test_domain_map_scatter.gd")
const TestDomainScatterBrushScript = preload("res://tests/domain/test_domain_scatter_brush.gd")
const TestDomainEntityArchetypesScript = preload("res://tests/domain/test_domain_entity_archetypes.gd")
const TestDomainMapEntitiesScript = preload("res://tests/domain/test_domain_map_entities.gd")
const TestDomainMapScatterRemovedScript = preload("res://tests/domain/test_domain_map_scatter_removed.gd")
const TestDomainTerrainScript = preload("res://tests/domain/test_domain_terrain.gd")
const TestDomainTerrainMaterialsScript = preload("res://tests/domain/test_domain_terrain_materials.gd")
const TestDomainTerrainTexturesScript = preload("res://tests/domain/test_domain_terrain_textures.gd")
const TestSurfaceStateScript = preload("res://tests/features/world/test_surface_state.gd")
const TestTerrainMeshingScript = preload("res://tests/features/world/test_terrain_meshing.gd")
const TestTerrainBrushScript = preload("res://tests/features/world/test_terrain_brush.gd")
const TestMapDocumentScript = preload("res://tests/features/world/test_map_document.gd")
const TestCoverageLayerScript = preload("res://tests/features/world/test_coverage_layer.gd")
const TestWaterBrushScript = preload("res://tests/features/world/test_water_brush.gd")
const TestWaterFlowScript = preload("res://tests/features/world/test_water_flow.gd")
const TestMapEditorHistoryScript = preload("res://tests/features/world/test_map_editor_history.gd")
const TestDomainTerrainNavigationScript = preload("res://tests/domain/test_domain_terrain_navigation.gd")
const TestTerrainAnchorsScript = preload("res://tests/domain/test_terrain_anchors.gd")
const TestDomainWaterScript = preload("res://tests/domain/test_domain_water.gd")
const TestBuildingPlacementScript = preload("res://tests/domain/test_building_placement.gd")
const TestMapSpawnServiceScript = preload("res://tests/domain/test_map_spawn_service.gd")
const TestMapValidatorScript = preload("res://tests/domain/test_map_validator.gd")
const TestMapPartyStartAuthoringScript = preload("res://tests/domain/test_map_party_start_authoring.gd")
const TestMapEditorTestPointsScript = preload("res://tests/domain/test_map_editor_test_points.gd")
const TestMapTestRunServiceScript = preload("res://tests/domain/test_map_test_run_service.gd")
const TestMapScenarioScript = preload("res://tests/domain/test_map_scenario.gd")
const TestMapGenerationScript = preload("res://tests/domain/test_map_generation.gd")

const TestAIFrameworkScript = preload("res://tests/ai/test_ai_framework.gd")
const TestAINeedsScript = preload("res://tests/ai/test_ai_needs.gd")
const TestAIWorkProvidersScript = preload("res://tests/ai/test_ai_work_providers.gd")
const TestAILogisticsScript = preload("res://tests/ai/test_ai_logistics.gd")
const TestAIDomainScript = preload("res://tests/ai/test_ai_domain.gd")


const TestSaveLoadScript = preload("res://tests/test_save_load.gd")


func _init() -> void:
	print("==================================================")
	print("       GO TO HAPPYNESS - MASTER TEST RUNNER       ")
	print("==================================================")

	# 1. Run Domain Unit Tests
	print("\n[1/2] Running Domain Unit Tests...")
	TestDomainEconomyScript.run_all()
	TestDomainEnvironmentScript.run_tests()
	TestDomainRoutingScript.run_all()
	TestDomainConstructionScript.run_all()
	TestDomainLogisticsScript.run_all()
	TestDomainLaunchScript.run_all()
	TestDomainGameRuntimeScript.run_all()
	TestDomainNavigationScript.run_all()
	TestDomainBuildingEditorScript.run_all()
	TestZoneAuthoringInvariantsScript.run_all()
	TestDomainHousingBlueprintsScript.run_all()
	TestDomainWorldAssetsScript.run_all()
	TestDomainHarvestSourcesScript.run_all()
	TestDomainWanderHabitsScript.run_all()
	TestDomainEntityPlacementProbeScript.run_all()
	TestDomainSeasonalEntitiesScript.run_all()
	TestDomainBiomeFillScript.run_all()
	TestDomainMapScatterScript.run_all()
	TestDomainScatterBrushScript.run_all()
	TestDomainEntityArchetypesScript.run_all()
	TestDomainMapEntitiesScript.run_all()
	TestDomainMapScatterRemovedScript.run_all()
	TestDomainTerrainScript.run_all()
	TestDomainTerrainMaterialsScript.run_all()
	TestDomainTerrainTexturesScript.run_all()
	TestSurfaceStateScript.run_all()
	TestTerrainMeshingScript.run_all()
	TestTerrainBrushScript.run_all()
	TestMapDocumentScript.run_all()
	TestCoverageLayerScript.run_all()
	TestWaterBrushScript.run_all()
	TestWaterFlowScript.run_all()
	TestMapEditorHistoryScript.run_all()
	TestDomainTerrainNavigationScript.run_all()
	TestTerrainAnchorsScript.run_all()
	TestDomainWaterScript.run_all()
	TestBuildingPlacementScript.run_all()
	TestMapSpawnServiceScript.run_all()
	TestMapValidatorScript.run_all()
	TestMapPartyStartAuthoringScript.run_all()
	TestMapEditorTestPointsScript.run_all()
	TestMapTestRunServiceScript.run_all()
	TestMapScenarioScript.run_all()
	TestMapGenerationScript.run_all()
	TestSaveLoadScript.run_all()
	print("  => Domain Unit Tests PASSED.")



	# 2. Run AI Unit Tests
	print("\n[2/2] Running AI Unit Tests...")
	TestAIFrameworkScript.run_all()
	TestAINeedsScript.run_all()
	TestAIWorkProvidersScript.run_all()
	TestAILogisticsScript.run_all()
	TestAIDomainScript.run_all()
	print("  => AI Unit Tests PASSED.")

	print("\n==================================================")
	print(" SUCCESS: All Domain & AI test suites passed.")
	print("==================================================")

	quit(0)
